Importing necessary Libraries

In [0]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import Perceptron
from sklearn.neighbors import KNeighborsClassifier


Loading Read the Dataset

In [0]:
dataset = pd.read_csv("messidor_features.csv",names=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

X = dataset.drop(20, axis=1)
y = dataset[20]

Splitting Training and Testing Data(80-20)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Logistic Regression Implementation

In [0]:
def lin_reg(X_train, y_train,X_test):
  log_regressor = LogisticRegression(max_iter=2500)
  log_regressor.fit(X_train, y_train)
  p=log_regressor.predict(X_test)
  q=log_regressor.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Random Forest Implementation 

In [0]:
def RF(X_train, y_train,X_test):

  from sklearn.ensemble import RandomForestClassifier
  rf = RandomForestClassifier()
  rf.fit(X_train, y_train) 
  p=rf.predict(X_test)
  q=rf.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Naive Bayes Implementation

In [0]:
def NB(X_train, y_train,X_test):
  gnb = GaussianNB()
  gnb = gnb.fit(X_train, y_train)
  p=gnb.predict(X_test)
  q=gnb.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Perceptron Implementation:

In [0]:
def perceptron(X_train, y_train,X_test):
  rf = Perceptron()
  rf.fit(X_train, y_train) 
  p=rf.predict(X_test)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  q = rf.predict(X_train)
  return p,q

MultiLayer Perceptron Implementation

In [0]:
def MLP(X_train, y_train,X_test):
 
  from sklearn.neural_network import MLPClassifier
  clf = MLPClassifier(solver='adam',activation='tanh',alpha=1e-5,max_iter=20000,hidden_layer_sizes=(10,5))
  clf.fit(X, y)
  p = clf.predict(X_test)
  q = clf.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Support Vector Machine Implementation

In [0]:
def SVM(X_train, y_train,X_test):

  from sklearn.svm import SVC
  clf = SVC(gamma='auto')
  clf.fit(X_train, y_train)
  p = clf.predict(X_test)
  q = clf.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Radial Basis Function Implementation

In [0]:
def RBF(X_train, y_train,X_test):

  from sklearn.svm import SVC
  clf = SVC(gamma='auto',kernel='rbf')
  clf.fit(X_train, y_train)
  p = clf.predict(X_test)
  q = clf.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Decision Forest Implementation

In [0]:
def DT(X_train, y_train,X_test):

  dt = DecisionTreeClassifier()
  dt.fit(X_train,y_train)
  p = dt.predict(X_test)
  q = dt.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

K Neighbors Classifier Implementation:

In [0]:
def KNN(X_train, y_train,X_test):

  dt = KNeighborsClassifier()
  dt.fit(X_train,y_train)
  p = dt.predict(X_test)
  q = dt.predict(X_train)
  print(confusion_matrix(y_test, p, labels=None, sample_weight=None, normalize=None))
  #print(confusion_matrix(y_train, q, labels=None, sample_weight=None, normalize=None))
  return p,q

Measuring Accuracy 

In [0]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def accuracy(y_test,y_train,p,q):

  print("Accuracy: ",accuracy_score(y_test, p))
  print("Precision: ",precision_score(y_test, p))
  print("Recall: ",recall_score(y_test, p))
  print("F1 Score: ",f1_score(y_test, p))

Normalising the data 

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

Training and Testing the models with UnNormalized Data

In [0]:
X = dataset.drop(20, axis=1)
y = dataset[20]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

print("UnNormalized Data:")
print()

print("logistic Regression: ")
p,q = lin_reg(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
print()

print("Naive Bayes: ")
p,q = NB(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
#print(classification_report(y_test, p))
print()

print("Radial Basis Function: ")
p,q = RBF(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
#print(classification_report(y_test, p))
print()

print("Support Vector Machine: ")
p,q = SVM(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
#print(classification_report(y_test, p))
print()

print("Multi Layer Perceptron: ")
p,q = MLP(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
#print(classification_report(y_test, p))
print()

print("Random Forest: ")
p,q = RF(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
print()

print("Decision Tree: ")
p,q = DT(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
print()

print("Perceptron: ")
p,q = perceptron(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
print()

print("KNN: ")
p,q = KNN(X_train, y_train,X_test)
accuracy(y_test,y_train,p,q)
print()


UnNormalized Data:

logistic Regression: 
[[87 17]
 [46 81]]
Accuracy:  0.7272727272727273
Precision:  0.826530612244898
Recall:  0.6377952755905512
F1 Score:  0.72

Naive Bayes: 
[[99  5]
 [94 33]]
Accuracy:  0.5714285714285714
Precision:  0.868421052631579
Recall:  0.25984251968503935
F1 Score:  0.39999999999999997

Radial Basis Function: 
[[ 33  71]
 [ 26 101]]
Accuracy:  0.5800865800865801
Precision:  0.5872093023255814
Recall:  0.7952755905511811
F1 Score:  0.6755852842809366

Support Vector Machine: 
[[ 33  71]
 [ 26 101]]
Accuracy:  0.5800865800865801
Precision:  0.5872093023255814
Recall:  0.7952755905511811
F1 Score:  0.6755852842809366

Multi Layer Perceptron: 
[[91 13]
 [38 89]]
Accuracy:  0.7792207792207793
Precision:  0.8725490196078431
Recall:  0.7007874015748031
F1 Score:  0.777292576419214

Random Forest: 
[[69 35]
 [48 79]]
Accuracy:  0.6406926406926406
Precision:  0.6929824561403509
Recall:  0.6220472440944882
F1 Score:  0.6556016597510375

Decision Tree: 
[[65 39]
 [

Training and Testing the models with Normalised Data

In [0]:
import pandas
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC


dataset = pd.read_csv("messidor_features.csv",names=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

array = dataset.values
X = array[:,0:19]
Y = array[:,19]
# prepare configuration for cross validation test harness
seed = 7
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
# prepare models
models = []
models.append(('LR', LogisticRegression(max_iter=1500)))
models.append(('KNN', KNeighborsClassifier()))

models.append(('NB', GaussianNB()))
models.append(('RBF', SVC(kernel='rbf')))
models.append(('SVM', SVC()))
#models=[]
models.append(('CART', DecisionTreeClassifier()))
models.append(('Random Forest',RandomForestClassifier()))
models.append(('Perceptron',Perceptron()))
models.append(('MLP',MLPClassifier(solver='adam',activation='logistic',alpha=1e-5,max_iter=20000,hidden_layer_sizes=(10,5,2))))
# evaluate each model in turn
results = []
names = []
scoring = 'accuracy'
for name, model in models:
	kfold = model_selection.KFold(n_splits=10)
	cv_results = model_selection.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f " % (name,max(cv_results))
	print(msg)


LR: 0.791304 
KNN: 0.713043 
NB: 0.686957 
RBF: 0.791304 
SVM: 0.791304 
CART: 0.678261 
Random Forest: 0.741379 
Perceptron: 0.695652 
MLP: 0.800000 


Principal Component Analysis:

In [0]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
xr=pca.fit_transform(X,y)
array = dataset.values
X = xr
y = array[:,19]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


Training and Testing the models with Dimensionality reduced data


In [0]:
print("Dimensionality Reduced Data:(Using PCA)")

p,q = lin_reg(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("logistic Regression: ",ta,acc)

p,q = NB(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Naive Bayes: ",ta,acc)
#print(classification_report(y_test, p))

p,q = RBF(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Radial Basis Function: ",ta,acc)
#print(classification_report(y_test, p))

p,q = SVM(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Support Vector Machine: ",ta,acc)
#print(classification_report(y_test, p))

p,q = MLP(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Multi Layer Perceptron: ",ta,acc)
#print(classification_report(y_test, p))

p,q = RF(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Random Forest: ",ta,acc)

p,q = DT(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Decision Tree: ",ta,acc)

p,q = perceptron(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("Perceptron: ",ta,acc)

p,q = KNN(X_train, y_train,X_test)
ta,acc = accuracy(y_test,y_train,p,q)
print("KNN: ",ta,acc)

Dimensionality Reduced Data(using PCA):

logistic Regression: 
[[82 25]
 [42 82]]
Accuracy:  0.70995670995671
Precision:  0.7663551401869159
Recall:  0.6612903225806451
F1 Score:  0.70995670995671

Naive Bayes: 
[[101   6]
 [ 97  27]]
Accuracy:  0.5541125541125541
Precision:  0.8181818181818182
Recall:  0.21774193548387097
F1 Score:  0.3439490445859873

Radial Basis Function: 
[[ 25  82]
 [ 18 106]]
Accuracy:  0.5670995670995671
Precision:  0.5638297872340425
Recall:  0.8548387096774194
F1 Score:  0.6794871794871794

Support Vector Machine: 
[[ 25  82]
 [ 18 106]]
Accuracy:  0.5670995670995671
Precision:  0.5638297872340425
Recall:  0.8548387096774194
F1 Score:  0.6794871794871794

Multi Layer Perceptron: 
[[79 28]
 [37 87]]
Accuracy:  0.7186147186147186
Precision:  0.7565217391304347
Recall:  0.7016129032258065
F1 Score:  0.7280334728033472

Random Forest: 
[[74 33]
 [54 70]]
Accuracy:  0.6233766233766234
Precision:  0.6796116504854369
Recall:  0.5645161290322581
F1 Score:  0.61674008